{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "my-app.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "my-app.fullname" . }}-networkpolicy
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  {{- range .Values.networkPolicy.allowedIPs }}
  - from:
    - ipBlock:
        cidr: {{ . }}
    ports:
    - protocol: TCP
      port: {{ $.Values.service.port }}
  {{- end }}
{{- end }}